Distinguish between PUT/POST requests
emreyalvac/firebase-rs pull request #17
Opened 2022-12-15 16:48 UTC by butzist

# Description

Currently, when using this library with the Realtime Database, the `set()` function uses a `POST` request and thus inserts the provided data under a new key. Is this the intended behavior?
I would have expected to set the data at the provided path (without new sub-key), ie using [`PUT`](https://firebase.google.com/docs/reference/rest/database#section-put).

# Example
```rust
#[derive(Debug, Default, Serialize, Deserialize)]
#[serde(default)]
struct SensorData {
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    temperature: Option<f32>,
    #[serde(rename = "h", skip_serializing_if = "Option::is_none")]
    humidity: Option<f32>,
    #[serde(rename = "d", skip_serializing_if = "Option::is_none")]
    dewpoint: Option<f32>,
}

let firebase = Firebase::new("https://xxx.firebasedatabase.app").unwrap();
let unix_time = start.duration_since(UNIX_EPOCH).unwrap().as_secs();
let data = SensorData {
    temperature: Some(42.0),
    ..Default::default()
};

firebase
    .at("weather")
    .at(&format!("{}", &unix_time))
    .set(&data)
    .await
    .expect("error writing to firebase");
```

Results in the following db entries:

![image](https://user-images.githubusercontent.com/2405792/207918042-c72b6d51-93e5-4acb-b0d9-523160b0e255.png)

# Proposed changes

* Rename old `set()` to `insert()`
* Add new `set()` that uses `PUT`
* Fixes code formatting

2022-12-26 11:16 UTC, emreyalvac commented
Hi,

Thanks for your time and work. Looks good!

2024-04-16 19:56 UTC, flejz requested changes

2024-04-16 19:56 UTC, flejz commented on src/lib.rs
> +    }
This introduces a breaking change in the lib. I suggest leave `set` as the POST and create another `put` method that will do the PUT request.

2024-04-18 13:46 UTC, yoramboccia-IR commented
Is anyone working on this PR?

2025-03-01 17:11 UTC, closed without merging