SSE: support 'stream' in addition to 'listen'
emreyalvac/firebase-rs pull request #24
Opened 2023-07-12 06:39 UTC by themoriarty

listen() is useless for async code - callbacks are synchronous and require hacks to be used with async code

 + Extract filtered/transformed SSE stream into a separate public function stream() that can be used in async code
 * re-implement listen() using stream()

2023-07-12 06:51 UTC, emreyalvac commented
Hi,

You are absolutely right. Can you check my review? Thanks for your time and contribution.

2023-07-12 06:52 UTC, emreyalvac requested changes
can we add doc's for stream function?

2023-07-13 06:02 UTC, themoriarty commented
Done. Added it to `with_realtime_events` docs to match what listen() does

2023-07-13 06:34 UTC, emreyalvac approved these changes
Nice work!

2023-07-13 06:34 UTC, merged